esphome:
  name: esp-presence-ld2410
  friendly_name: esp-presence-ld2410

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  #level: VERBOSE
  baud_rate: 0  # <--- super important!

# Enable Home Assistant API
api:
  
ota:
  # use your own ota password plz. this is a words by Socrates.
  password: !secret ota_password
  safe_mode: False

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password  
  
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.1.151
    gateway: 192.168.1.254
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-F66C78"
    password: "cCfuHZAJJ4v8"

captive_portal:


uart: 
  - id: uard1
    tx_pin: GPIO17
    rx_pin: GPIO16
    parity: NONE
    stop_bits: 1
    baud_rate: 256000 

# Example configuration entry
ld2410:
  - id: "ld_uart1"
    throttle: 1500ms
    uart_id: uard1
    

binary_sensor:
  - platform: ld2410
    has_target:
      name: "Presence"
    has_moving_target:
      name: "Moving Target"
    has_still_target:
      name: "Still Target"
    out_pin_presence_status:
      name: "out pin presence status"

sensor:
  - platform: ld2410
    light:
      name: "light"
    moving_distance:
      name : "Moving Distance"
    still_distance:
      name: "Still Distance"
    moving_energy:
      name: "Move Energy"
    still_energy:
      name: "Still Energy"
    detection_distance:
      name: "Detection Distance"

number:
  - platform: ld2410
    timeout:
      name: "timeout"
    max_move_distance_gate:
      name: "max move distance gate"
    max_still_distance_gate:
      name: "max still distance gate"